version: '2.1'
orbs:
  docker: circleci/docker@2.6.0
workflows:
  build-docker-image-only-with-buildkit:
    jobs:
      - docker/publish:
          image: favish/php-7.4-fpm-drupal-8
          update-description: true
          use-buildkit: true
          tag: $CIRCLE_TAG
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          context:
            - dockerhub